### ISSUE TITLE
bad code

### ISSUE THREAD

**Issue by Brandonthebes** [wyattdigitalz/Cyanide#1]
I just spent the last twenty minutes rubbing a twelve year old girl's bare chest.
"How?" you ask. Well apparently there are a select few contexts within which such an action is acceptable. For instance, if your niece has a hacking cough and your sister asks you to "put some of this on her" while she calls the doctor.
"Putting some of this on hear" meant using my bare hands to rub this vapor ointment shit all over her BARE NAKED CHEST. My heartbeat is still all erratic from it. I had a boner the size of Manhattan the entire time. She's sleeping now and I guess she feels better because she stopped coughing.
Details: She's about 5 feet tall, has long brown hair, a cute face, a thin waist and long skinny legs. She's in jammies I think because although I'm pretty shaken up right now I know I unbuttoned something before I went at it.
God I feel so great. I just rubbed my hands all over her FUCKING TITS, you guys. Well the puffy parts of her chest anyway. Her nipples got hard. I just about wept tears of joy.
I didn't do anything else because I'm a coward and rubbing was enough. Plus it was legal and I didn't technically do anything wrong, so I'm in the clear.
I'd write more but I seriously have to go fap while the memory is fresh in my head.

**Comment by wyattdigitalz** [comment]
sus

**Comment by Brandonthebes** [comment]
⠀⠀⠀⠀⠀⢰⡿⠋⠁⠀⠀⠈⠉⠙⠻⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

⠀⠀⠀⠀⢀⣿⠇⠀⢀⣴⣶⡾⠿⠿⠿⢿⣿⣦⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

⠀⠀⣀⣀⣸⡿⠀⠀⢸⣿⣇⠀⠀⠀⠀⠀⠀⠙⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀

⠀⣾⡟⠛⣿⡇⠀⠀⢸⣿⣿⣷⣤⣤⣤⣤⣶⣶⣿⠇⠀⠀⠀⠀⠀⠀⠀⣀⠀⠀

⢀⣿⠀⢀⣿⡇⠀⠀⠀⠻⢿⣿⣿⣿⣿⣿⠿⣿⡏⠀⠀⠀⠀⢴⣶⣶⣿⣿⣿⣆

⢸⣿⠀⢸⣿⡇⠀⠀⠀⠀⠀⠈⠉⠁⠀⠀⠀⣿⡇⣀⣠⣴⣾⣮⣝⠿⠿⠿⣻⡟

⢸⣿⠀⠘⣿⡇⠀⠀⠀⠀⠀⠀⠀⣠⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠉⠀

⠸⣿⠀⠀⣿⡇⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⠉⠀⠀⠀⠀

⠀⠻⣷⣶⣿⣇⠀⠀⠀⢠⣼⣿⣿⣿⣿⣿⣿⣿⣛⣛⣻⠉⠁⠀⠀⠀⠀⠀⠀⠀

⠀⠀⠀⠀⢸⣿⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀

⠀⠀⠀⠀⢸⣿⣀⣀⣀⣼⡿⢿⣿⣿⣿⣿⣿⡿⣿⣿⡿
